In [1]:
import pandas as pd
import numpy as np
from scipy import sparse
from sklearn.preprocessing import normalize
from tqdm.notebook import tqdm

In [2]:
train_joke_df = pd.read_csv(r'data\recsys-in-practice\train_joke_df.csv')

In [32]:
test_joke_df_nofactrating = pd.read_csv(r'data\recsys-in-practice\test_joke_df_nofactrating.csv', index_col=0)


In [5]:
rows, r_pos = np.unique(train_joke_df.values[:,0], return_inverse=True)
cols, c_pos = np.unique(train_joke_df.values[:,1], return_inverse=True)

In [6]:
interactions_sparse = sparse.csr_matrix((train_joke_df.values[:,2], (r_pos, c_pos)) )

In [7]:
interactions_sparse

<24983x100 sparse matrix of type '<class 'numpy.float64'>'
	with 1448364 stored elements in Compressed Sparse Row format>

In [8]:
Pui = normalize(interactions_sparse, norm='l2', axis=1)


#Похожесть айтемов между собой
sim = Pui.T * Pui

In [9]:
#Похожесть юзеров между собой
sim_users = Pui * Pui.T
sim_users

<24983x24983 sparse matrix of type '<class 'numpy.float64'>'
	with 624150287 stored elements in Compressed Sparse Row format>

In [11]:
sim_users[0].todense()

matrix([[ 1.        , -0.32886076, -0.05105598, ...,  0.04466449,
          0.13495061,  0.00450064]])

In [12]:
sim_users[1].todense()

matrix([[-0.32886076,  1.        ,  0.1048572 , ...,  0.03399436,
          0.08046437, -0.09067869]])

In [13]:
sim[0].todense()

matrix([[191.07311367,  60.43840259,  52.83384167,  28.04325073,
          24.20506023,  31.99753946,  26.75149782,  22.71598567,
          36.12964816,  53.13055994,  42.88534622,  34.60076924,
          11.61206151,  31.98162676,  15.36565396,  -1.38043076,
          -0.4595844 ,  21.4952042 ,   9.33921007,   4.21899774,
          31.83512362,  41.1909143 ,  39.24330865,  26.70612458,
          43.16902966,  31.79947415,  37.67814938,  30.34399662,
          41.16226781,  29.9540124 ,  38.41047716,  33.31608312,
          33.79706252,  31.60737719,  40.37688215,  43.45939253,
          35.79970727,  47.73466586,  29.17191896,  41.19286054,
          38.46213332,  30.59616699,  32.36762102,  30.29309382,
          40.79077987,  40.64103769,  26.71093908,  37.92447245,
          33.19954096,  40.69990432,  27.73166011,  28.87218379,
          30.59799074,  32.5245291 ,  41.14723434,  38.50738234,
          26.03686651,   6.18778783,  33.39123887,  43.02921597,
          34.11394525,  3

In [14]:
sim[1].todense()

matrix([[ 60.43840259, 255.13400129,  47.34599805,  42.17122746,
          35.93679996,  33.72536026,  34.15082618,  18.952618  ,
          31.30137046,  48.40225002,  48.03973384,  50.17133963,
          30.4541686 ,  53.78976765,  22.65557587,   2.9522168 ,
          15.0966236 ,  19.38169812,   9.55430045,  10.60698601,
          47.9172747 ,  52.03178739,  39.48661494,  25.57735813,
          67.24750414,  54.61200355,  33.49978603,  25.23996227,
          56.60236092,  30.40632464,  49.79722229,  26.94440293,
          41.5339028 ,  43.88774106,  43.28724243,  35.4423671 ,
          42.615765  ,  45.47604235,  45.9069255 ,  47.31046378,
          47.54681634,  41.75542791,  29.05783431,  28.73279776,
          46.76902764,  44.33341236,  21.48326177,  34.28505528,
          30.90320607,  39.86579993,  54.36136748,  53.55896835,
          40.50055372,  29.19396134,  35.69046317,  49.28430042,
          25.51979698,  16.88704752,  37.77728625,  36.82166587,
          36.02732052,  2

In [ ]:
sim.todense().shape

In [ ]:
sim.todense()

In [27]:
[i+1 for i in sim_users[0].toarray().argsort()[0][-20:]]

[3914,
 18217,
 8800,
 13711,
 9985,
 19185,
 8157,
 15952,
 23897,
 13691,
 1584,
 18179,
 4499,
 8334,
 18058,
 15460,
 15046,
 2336,
 6671,
 1]

In [16]:
train_joke_df_grouped = train_joke_df.groupby(by='UID').agg({'JID':list})

In [19]:
train_joke_df_grouped

JID
UID                                                     
1      [53, 30, 15, 7, 29, 38, 20, 32, 54, 59, 3, 82,...
2      [4, 10, 6, 32, 26, 2, 13, 21, 69, 38, 61, 65, ...
3      [18, 60, 90, 15, 16, 54, 45, 11, 31, 39, 43, 1...
4      [17, 20, 16, 62, 21, 10, 36, 7, 42, 11, 61, 65...
5      [57, 82, 90, 20, 51, 95, 50, 77, 12, 45, 16, 5...
...                                                  ...
24979  [38, 66, 94, 61, 28, 80, 83, 7, 62, 18, 17, 32...
24980  [9, 58, 56, 53, 27, 35, 31, 29, 68, 59, 94, 10...
24981  [35, 49, 38, 54, 13, 41, 14, 56, 72, 20, 17, 6...
24982  [21, 17, 15, 55, 61, 49, 56, 68, 7, 66, 48, 18...
24983  [3, 66, 33, 62, 5, 31, 39, 27, 29, 24, 18, 67,...

[24983 rows x 1 columns]

In [30]:
np.sort(train_joke_df_grouped.loc[1].values[0])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 12, 13, 14, 15, 16, 17, 18,
       20, 21, 22, 23, 24, 26, 27, 28, 29, 30, 32, 33, 35, 36, 37, 38, 41,
       42, 43, 44, 45, 47, 48, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 61,
       62, 63, 64, 66, 67, 68, 69, 70, 78, 82, 97])

In [31]:
np.sort(train_joke_df_grouped.loc[6671].values[0])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 28, 29, 31, 32, 33, 34, 35, 36, 37,
       38, 39, 40, 41, 42, 43, 44, 45, 46, 48, 49, 51, 52, 54, 55, 56, 57,
       58, 59, 61, 63, 64, 65, 67, 69, 70, 89])

In [45]:
xx = [i for i in sim_users[11228].toarray().argsort()[0][-3:]]

xx

[8769, 6436, 11228]

In [46]:
yy = [i for i in sim[39].toarray().argsort()[0][-3:]]
yy

[10, 20, 39]

In [47]:
ratings = []
for x in xx:
    for y in yy:
        ratings.append(interactions_sparse[x, y])
ratings   

[0.0, 7.52, 0.0, 3.35, 8.45, 3.64, -0.34, 8.11, -7.18]

In [53]:
train_joke_df.loc[(train_joke_df.UID == 11228) & (train_joke_df.JID == 39)].values

array([], shape=(0, 3), dtype=float64)

In [56]:
train_joke_df.loc[(train_joke_df.UID == 11229) & (train_joke_df.JID == 6)].values[0][2]

8.5

In [ ]:
n_neig = 3

result = []
err = 0
err_list = []
for i, row in enumerate(tqdm(test_joke_df_nofactrating.values)):
    user = int(row[0])
    joke = int(row[1])
    
    user_id = int(row[0]) - 1
    joke_id = int(row[1]) - 1
    
    sim_jokes = [i for i in sim[joke_id].toarray().argsort()[0][-n_neig:]]
    ratings = []
    
    for j in sim_jokes:
        rating_df = train_joke_df.loc[(train_joke_df.UID == user) & (train_joke_df.JID == joke)].values
        if len(rating) > 0:
            rating = rating_df[0][2]
            ratings.append(rating)
            
    result.append(np.mean(ratings))

In [33]:
test_joke_df_nofactrating

UID  JID
InteractionID            
0              11228   39
1              21724   85
2              16782   56
3              12105   42
4              14427    2
...              ...  ...
362086          3085   66
362087         13765   31
362088         10341   29
362089          3553    8
362090          1199   67

[362091 rows x 2 columns]

In [ ]:
sim[0].todense()

In [ ]:
sim[22].todense()

In [ ]:
interactions_sparse_transposed = interactions_sparse.transpose(copy=True)
Piu = normalize(interactions_sparse_transposed, norm='l1', axis=1)

In [ ]:
#https://nms.kcl.ac.uk/colin.cooper/papers/recommender-rw.pdf
#Случайный обход графа
#Результат - матрица с большим количеством элементов, мы попытались восстановить пропуски
# в оценках пользователей для айтемов
fit = Pui * Piu * Pui


In [ ]:
fit

In [ ]:
result = []
err = 0
err_list = []
for i, row in enumerate(tqdm(test_joke_df_nofactrating.values)):
    try:
        user_id = int(row[0]) - 1
        joke_id = int(row[1]) - 1
        r = fit[user_id].toarray()[joke_id]
        result.append(r)
    except Exception as ex:
        result.append(0)
        err += 1
        err_list.append(i)

In [ ]:
err, err_list[:10]

In [ ]:
test_joke_df_nofactrating['Rating'] = result
test_joke_df_nofactrating

In [ ]:
test_joke_df_nofactrating['Rating'].to_frame().to_csv('graph_rec.csv')

In [ ]:
init_set = set([titles_dict[i+1] for i in np.nonzero(interactions_sparse[520])[1].tolist()])

In [ ]:
predict_set = set([titles_dict[i+1] for i in fit[520].toarray().argsort()[0][-70:].tolist()])

In [ ]:
predict_set - init_set